version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://doordash-json-landing-bucket
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-filter-lambda-function --s3-bucket doordash-json-landing-bucket --s3-key deployment_package.zip
      - echo "Invoking Lambda function to upload filtered data to S3..."
      - aws lambda invoke --function-name doordash-filter-lambda-function --payload '{}' response.json
      - |
        for file in $(jq -r '.files[]' response.json); do
          aws s3 cp $file s3://doordash-filtered-target-bucket/
        done
      - echo "Deployment complete!"